version: '3.8'

services:
  timesheet-dev:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
      cache_from:
        - timesheet:dev-cache
      args:
        - GA_NPM_TOKEN=${GA_NPM_TOKEN}
    image: timesheet:dev
    container_name: timesheet-dev
    env_file:
      - .env
    networks:
      - timesheet-net
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true

  timesheet-prod:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
      cache_from:
        - timesheet:prod-cache
      args:
        - GA_NPM_TOKEN=${GA_NPM_TOKEN}
    image: timesheet:prod
    container_name: timesheet-prod
    env_file:
      - .env
    networks:
      - timesheet-net
    ports:
      - 3001:3000
    restart: unless-stopped
    environment:
      - NODE_ENV=production

networks:
  timesheet-net:
    driver: bridge
