-- AlterTable
ALTER TABLE "User" ALTER COLUMN "lastLoginDate" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "created" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "lastLogin" SET DATA TYPE TIMESTAMPTZ(3);
